---

- name: "1.4.1 | PATCH | Ensure bootloader password is set"
  debug: 
    msg: |
      Create an encrypted password with grub-mkpasswd-pbkdf2 :
      # grub-mkpasswd-pbkdf2
      Enter password: <password>
      Reenter password: <password>
      PBKDF2 hash of your password is <encrypted-password>
      Add the following into a custom /etc/grub.d configuration file:
      cat <<EOF
      set superusers="<username>"
      password_pbkdf2 <username> <encrypted-password>
      EOF
      More info: https://help.ubuntu.com/community/Grub2/Passwords
  when:
      - ubtu22cis_set_boot_pass
      - ubtu22cis_rule_1_4_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.4.1
      - grub

- name: "1.4.2 | PATCH | Ensure permissions on bootloader config are configured"
  block:
      - name: "1.4.2 | AUDIT | Ensure permissions on bootloader config are configured | Check for Grub file"
        ansible.builtin.stat:
            path: "{{ ubtu22cis_grub_file }}"
        check_mode: false
        register: ubtu22cis_1_4_2_grub_cfg_status

      - name: "1.4.2 | PATCH | Ensure permissions on bootloader config are configured | Set permissions"
        ansible.builtin.file:
            path: "{{ ubtu22cis_grub_file }}"
            owner: root
            group: root
            mode: 0400
        when:
            - ubtu22cis_1_4_2_grub_cfg_status.stat.exists
  when:
      - ubtu22cis_rule_1_4_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.4.2
      - grub

- name: "1.4.3 | PATCH | Ensure authentication required for single user mode"
  ansible.builtin.user:
      name: "{{ ubtu22cis_grub_user }}"
      password: "{{ ubtu22cis_bootloader_password_hash }}"
  when:
      - ubtu22cis_rule_1_4_3
      - ubtu22cis_set_boot_pass
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.4.3
      - passwd
