---
- name: "1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled"
  block:
      - name: "1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled | Edit modprobe config"
        ansible.builtin.lineinfile:
            dest: /etc/modprobe.d/cramfs.conf
            regexp: '^(#)?install cramfs(\\s|$)'
            line: "{{ item }}"
            create: true
        loop:
            - install cramfs /bin/true
            - blacklist cramfs

      - name: "1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled | Disable cramfs"
        community.general.modprobe:
            name: "cramfs"
            state: absent
        when: ansible_connection != 'docker'
  when:
      - ubtu22cis_rule_1_1_1_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.1.1
      - cramfs

- name: "1.1.1.2 | PATCH | Ensure mounting of squashfs filesystems is disabled"
  block:
      - name: "1.1.1.2 | PATCH | Ensure mounting of squashfs filesystems is disabled | Edit modprobe config"
        ansible.builtin.lineinfile:
            dest: /etc/modprobe.d/squashfs.conf
            regexp: '^(#)?install squashfs(\\s|$)'
            line: "{{ item }}"
            create: true
        loop:
            - install squashfs /bin/false
            - blacklist squashfs

      - name: "1.1.1.2 | PATCH | Ensure mounting of squashfs filesystems is disabled | Disable squashfs"
        community.general.modprobe:
            name: squashfs
            state: absent
        when: ansible_connection != 'docker'
  when:
      - ubtu22cis_rule_1_1_1_2
      - not snap_pkg_mgr.stat.exists
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_1.1.1.2
      - squashfs

- name: "1.1.1.3 | PATCH | Ensure mounting of udf filesystems is disabled"
  block:
      - name: "1.1.1.3 | PATCH | Ensure mounting of udf filesystems is disabled | Edit modprobe config"
        ansible.builtin.lineinfile:
            dest: /etc/modprobe.d/udf.conf
            regexp: '^(#)?install udf(\\s|$)'
            line: "{{ item }}"
            create: true
        loop:
            - install udf /bin/true
            - blacklist udf

      - name: "1.1.1.3 | PATCH | Ensure mounting of udf filesystems is disabled | Disable udf"
        community.general.modprobe:
            name: udf
            state: absent
        when: ansible_connection != 'docker'
  when:
      - ubtu22cis_rule_1_1_1_3
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_1.1.1.3
      - udf
